version: '3.3'

services:
  web:
    image: nginx
    ports:
      - 8080:80
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == worker
